create schema if not exists private;

revoke all on schema private from public, anon, authenticated;
grant usage on schema private to authenticated;
grant usage on schema private to service_role;

create table if not exists private.ai_scan_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  mode text not null check (mode in ('barcode', 'expiration')),
  request_bytes integer not null check (request_bytes > 0),
  created_at timestamptz not null default timezone('utc', now())
);

revoke all on private.ai_scan_events from public, anon, authenticated;

create index if not exists ai_scan_events_user_created_at_idx
  on private.ai_scan_events (user_id, created_at desc);
